### ISSUE TITLE
Program crashes _sometimes_ when all/single sensor is triggered

### ISSUE THREAD

**Issue by ga32xan** [ga32xan/Maxigauge-TPG256A#18]
Program crashes _sometimes_ when all/single sensor is triggered
* Doesn't happen every time though
* Only sometimes? Maybe when one hits the wrong stage in the program execution time?

**Comment by ga32xan** [comment]
02-01-2018 11-32-33 - control.log
```
02-01-2018 11:36:40 CTS line: False
02-01-2018 11:36:40 DSR line: False
02-01-2018 11:36:40 Send Command: b'PR5\r\n'
02-01-2018 11:36:40 ##########ser_command##############
02-01-2018 11:36:40 Command string: b'\x05'
02-01-2018 11:36:40 ##########to_serial##############
02-01-2018 11:36:40 byte-input (as str repre): 
02-01-2018 11:36:40 CTS line: False
02-01-2018 11:36:40 DSR line: False
02-01-2018 11:36:40 Send Command: b'\x05'
02-01-2018 11:36:40 ##########splitting received pressure string##############
02-01-2018 11:36:40 ##########read_port##############
02-01-2018 11:36:40 Am I outWaiting?: 0
02-01-2018 11:36:40 Am I inWaiting?: 0
02-01-2018 11:36:40 Input buffer size: 0
02-01-2018 11:36:40 CTS line: False
02-01-2018 11:36:40 DSR line: False
02-01-2018 11:36:40 No data in input buffer...No data received
02-01-2018 11:36:40 ['']
```

**Comment by ga32xan** [comment]
console output
```
-v debug 
change channels during program execution
02-01-2018 11:36:37:     ... running ...
Program Logging goes to  : C:\Users\ltstm\Desktop\test\02-01-2018 11-32-33 - control.log
Pressure Logging goes to : C:\Users\ltstm\Desktop\test\02-01-2018 11-32-33 - pressure.log
#################################################################################################
#       STM     |       ROU     |       PREP    |       AUX     |       CH 5    |       CH 6    #
#     5.589e-09 |     0.5606    |     1.947e-05 |       NAN     |       NAN     |       NAN     #
#################################################################################################
Traceback (most recent call last):
  File "Maxigauge-TPG256A.py", line 456, in <module>
    status,pre = read_gauges(ser)
  File "Maxigauge-TPG256A.py", line 147, in read_gauges
    string_pres=str(string[1])          #pressure value converted to string
IndexError: list index out of range
```
